### ISSUE TITLE
ToolDebug: use yaml to configure processes

### ISSUE THREAD

**Issue by cheesasaurus** [cheesasaurus/twcheese#40]
the current way with method chaining, callbacks, builders, etc is a hideous mess.

e.g. (bad)
```javascript
debugProcess.enqueuePhase(
    PhaseQuestion.create('Entry')
        .addQuestion(Question.create(`What's broken?`)
            .addOption(Option.create('Wrong values shown in commands list', 'wrong_values')
                .addFollowUp(PhaseAttempt.create('determine command url', trySelectCommandFromTable)
                    .setInstructions('Select a problematic row.')
                    .onSuccess(function(commandUrl) {
                        debugProcess.insertPhase(PhaseAttempt.create('read selected command', async () => tryScrapeCommandScreen(commandUrl))
                            .setDataSummarizer(summarizeTryScrapeCommandScreen)
                            .onSuccess(function(d) {
                                debugProcess.insertPhase(PhaseQuestion.create('Command scraper')
                                    .lookAt(d.document.documentElement.outerHTML)
                                    .addQuestion(QuestionValue.create('Arrival', d.command.arrival))
                                    .addQuestion(QuestionValue.create('Haul', d.command.haul))
                                    .addQuestion(QuestionValue.create('Haul capacity', d.command.haulCapacity))
                                )
                            })
                        )
                    })
                )
            )
            .addOption(Option.create('Something else', 'other'))
        )
    )
    .enqueuePhase(PhaseQuestion.create('extra info')
        .addQuestion(QuestionFreeForm.create('Additional information', 'e.g. "iron isn\'t shown"'))
    )
    .enqueuePhase(PhaseReport.create(bugReporter));
```
easier to reason about:
```yaml
PhaseQuestion
  name: Entry
  questions:
    - Question
      ask: What's broken?
      options:
        - Option
          answer: Wrong values shown in commands list
          value: wrong_values
          followUp:
            - PhaseAttempt
              name: Determine command url
              action: trySelectCommandFromTable
              instructions: Select a problematic row.
              success:
                - PhaseAttempt
                  name: Read selected command
                  action: tryScrapeCommandScreen
                  summarizeAction: summarizeTryScrapeCommandScreen
                  success:
                    - PhaseQuestion
                      name: Command scraper
                      lookAt: input.document.documentElement.outerHTML
                      questions:
                        - QuestionValue
                          ask: Arrival
                          examine: input.command.arrival
                        - QuestionValue
                          ask: Haul
                          examine: input.command.haul
                        - QuestionValue
                          ask: Haul capacity
                          examine: input.command.haulCapacity                
        - Option
          answer: Something else
          value: other
PhaseReport
  bugReporter: myBugReporter
```

where `input` is the output value from the closest parent PhaseAttempt

__idea__
builder can receive map of named references. e.g.
```javascript
{
    trySelectCommandFromTable: (in) => {
        /*...*/
        return out;
    };
    tryScrapeCommandScreen: (in) => {
        /*...*/
        return out;
    };
}
```
1. yaml parser creates json
2. new config object from json
3. builder uses config object and mapping of references to create a DebugProcess
